# Generated by Django 3.2.20 on 2023-07-13 13:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('all_approved_comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
