# Generated by Django 3.2.20 on 2023-07-16 18:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
